version: '3.0'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./db/sql/noaa.sql:/docker-entrypoint-initdb.d/noaa.sql


  db_uploader:
    expose:
      - 8080
    restart: on-failure
    command: ["python", "./db_upload.py"]
    command: ["python", "./db_upload.py"]
    ports:
      - "8080:8080"
    build: ./db
    depends_on:
      - db
    links:
      - db
    volumes:
     - ./db:/code

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - db_uploader
    links:
      - db
    volumes:
     - ./app:/code
    
